---
 - hosts:  all
   vars:  
     log_file:  /tmp/testlog.txt
   tasks:
    - name: copy the file
      copy:
        src: /home/ansible/copy.txt
        dest: "{{ log_file }}"
    - name:  Download logstash rpm package
      get_url:
        url:  https://artifacts.elastic.co/downloads/logstash/logstash-5.3.1.rpm 
        dest:  /opt/logstash-5.3.1.rpm
    - name: Install package.
      yum:
        name: /opt/logstash-5.3.1.rpm
        state: present  
    - name:  start the service 
      service:
        name:  logstash
        state:  started
    - name:  template for logstash.yml for remote
      template:  
        src:  logstash.yml.j2
        dest:  /etc/logstash/logstash.yml
        force:  yes 
      when:  ansible_default_ipv4.address == '172.31.23.242'
    - name:  template for logstash.yml for local
      template:
        src:  logstash_local.yml.j2
        dest:  /etc/logstash/logstash.yml
        force:  yes
      when:  ansible_default_ipv4.address == '172.31.18.198'
