---
 - hosts:  remote
   tasks:
    - name: copy the file
      copy:
        src: /home/ansible/copy.txt
        dest: {{ copy_file }}
    - name:  Download kibana rpm package
      get_url:
        url:  https://artifacts.elastic.co/downloads/kibana/kibana-5.3.1-x86_64.rpm 
        dest:  /opt/kibana-5.3.1.rpm
    - name: Install package.
      yum:
        name: /opt/kibana-5.3.1.rpm
        state: present  
    - name:  start the service 
      service:
        name:  kibana
        state:  started
